### ISSUE TITLE
很高兴看到有关Symfony的开源项目。

### ISSUE THREAD

**Issue by CJayHe** [siganushka/generic-bundle#1]
很高兴看到有关Symfony的开源项目。

**Comment by CJayHe** [comment]
您应该完善您readme。让人了解你的项目以及如何使用。使用之后的效果。

**Comment by siganushka** [comment]
> 您应该完善您readme。让人了解你的项目以及如何使用。使用之后的效果。

你应该看到我有几个 bundle 和 packages 都没有好好写 README.md，是因为这些组件还没达到发布的状态，我在自己多个项目里在使用、锤炼中。

**Comment by CJayHe** [comment]
嗯，期待您的发布。

**Comment by siganushka** [comment]
close issues.
